apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rz8cm77dk-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rz8cm77dk-nodejs 
  name: rz8cm77dk-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rz8cm77dk-nodejs 
